IF OBJECT_ID(N'chrn01.CustomerSnapshot', N'U') IS NULL
BEGIN
CREATE TABLE [chrn01].[CustomerSnapshot]
(
    [SnapshotDate] date NOT NULL,
    [CustomerId] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [LastOrderDate] date NULL,
    [Recency_Orders_Days] int NULL,
    [Recency_MaintOrders_Days] int NULL,
    [Recency_Invoices_Days] int NULL,
    [OrderValue_90d] decimal(18,2) NULL,
    [OrderFreq_90d] int NULL,
    [MaintOrderValue_90d] decimal(18,2) NULL,
    [ProdOrderValue_90d] decimal(18,2) NULL,
    [BackorderCount_180dPlus] int NULL,
    [UnpaidInv_OverTerms_Count] int NULL,
    [UnpaidInv_90plus_Count] int NULL,
    [ReturnInvCount_90d] int NULL,
    [ChurnIf_NoOrd90] bit NULL,
    [ChurnIf_NoInv90] bit NULL,
    [ChurnIf_NoMaintOrd90_WithinGrace] bit NULL,
    [PredChurn_Unpaid90plus] bit NULL,
    [PredChurn_HighBackorders] bit NULL,
    [KnownChurn_Confirmed] bit NULL,
    [CreditValue_90d] decimal(18,2) NULL,
    [CreditCount_90d] int NULL,
    [OrderValue_Prev90d] decimal(18,2) NULL,
    [OrderFreq_Prev90d] int NULL,
    [OrderValue_3m_Change] decimal(18,2) NULL,
    [OrderValue_3m_ChangePct] decimal(9,4) NULL,
    [OrderFreq_3m_Change] int NULL,
    [OrderFreq_3m_ChangePct] decimal(9,4) NULL,
    [ProdRatio_90d] decimal(9,4) NULL,
    [MaintRatio_90d] decimal(9,4) NULL,
    [IsProductHeavy_90d] bit NULL,
    [IsMaintHeavy_90d] bit NULL,
    [Eox_MinDaysToLDOS] int NULL,
    [Risk_EoX_12m] bit NULL,
    [Risk_EoX_6m] bit NULL,
    [Risk_EoX_3m] bit NULL,
    [PredChurn_EoXExpired] bit NULL,
    [KnownChurn_Effective] bit NULL,
    [UpcomingChurn_90d] bit NULL,
    [ARBucket_Current_Count] int NULL,
    [ARBucket_1_30_Count] int NULL,
    [ARBucket_31_60_Count] int NULL,
    [ARBucket_61_90_Count] int NULL,
    [ARBucket_91_120_Count] int NULL,
    [ARBucket_121_180_Count] int NULL,
    [ARBucket_180Plus_Count] int NULL,
    [DSO_OpenInvoices] decimal(9,2) NULL,
    [Target_IsChurned_3mAhead] bit NULL,
    [Target_IsChurned_6mAhead] bit NULL,
    [Target_IsChurned_12mAhead] bit NULL,
    [Eox_Rev_Expired_12m] decimal(18,2) NULL,
    [Eox_Rev_Risk12m] decimal(18,2) NULL,
    [Eox_Rev_Total12m] decimal(18,2) NULL,
    [Eox_RevExpiredPct_12m] decimal(9,4) NULL,
    [Eox_RevRiskPct_12m] decimal(9,4) NULL,
    [Eox_HasExpiredRevenue_12m] int NULL,
    [Eox_HasRiskRevenue_12m] int NULL,
    [Eox_MajorityExpired_12m] int NULL,
    [Eox_SKU_CountExpired] int NULL,
    [Eox_SKU_CountRisk12m] int NULL,
    [Eox_MinLDOSDate] date NULL,
    [EoxExpired_NoOrders90d] int NULL,
    [EoxRisk_NoMaintRenewal] int NULL,
    [EoxExpired_UnpaidInv90plus] int NULL,
    [EoxExpired_CreditSpike90d] int NULL,
    [MaintContractActive] bit NOT NULL CONSTRAINT [DF_CustomerSnapshot_MaintContractActive] DEFAULT ((0)),
    CONSTRAINT [PK_CustomerSnapshot] PRIMARY KEY CLUSTERED ([SnapshotDate] ASC, [CustomerId] ASC)
);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CustomerSnapshot_SnapshotDate_CustomerId' AND object_id = OBJECT_ID(N'chrn01.CustomerSnapshot'))
    CREATE NONCLUSTERED INDEX [IX_CustomerSnapshot_SnapshotDate_CustomerId] ON [chrn01].[CustomerSnapshot] ([SnapshotDate] ASC, [CustomerId] ASC);
GO
